set(kortex_SOURCES
  src/check.cc
  src/color.cc
  src/fileio.cc
  src/filter.cc
  src/image.cc
  src/image_conversion.cc
  src/image_io.cc
  src/image_io_jpg.cc
  src/image_io_png.cc
  src/image_io_pnm.cc
  src/image_paint.cc
  src/image_processing.cc
  src/indexed_types.cc
  src/kmatrix.cc
  src/linear_algebra.cc
  src/log_manager.cc
  src/math.cc
  src/matrix.cc
  src/mem_manager.cc
  src/mem_unit.cc
  src/message.cc
  src/minmax.cc
  src/progress_bar.cc
  src/random.cc
  src/rect2.cc
  src/rotation.cc
  src/sorting.cc
  src/sse_extensions.cc
  src/string.cc
  src/svd.cc
  src/timer.cc
)

set(kortex_HEADERS
  kortex/include/bit_operations.h
  kortex/include/check.h
  kortex/include/color.h
  kortex/include/defs.h
  kortex/include/fileio.h
  kortex/include/filter.h
  kortex/include/image_conversion.h
  kortex/include/image.h
  kortex/include/image_io.h
  kortex/include/image_io_jpg.h
  kortex/include/image_io_png.h
  kortex/include/image_io_pnm.h
  kortex/include/image_paint.h
  kortex/include/image_processing.h
  kortex/include/indexed_types.h
  kortex/include/kmatrix.h
  kortex/include/lapack_externs.h
  kortex/include/linear_algebra.h
  kortex/include/log_manager.h
  kortex/include/math.h
  kortex/include/matrix.h
  kortex/include/mem_manager.h
  kortex/include/mem_unit.h
  kortex/include/message.h
  kortex/include/minmax.h
  kortex/include/progress_bar.h
  kortex/include/random.h
  kortex/include/rect2.h
  kortex/include/rotation.h
  kortex/include/sorting.h
  kortex/include/sse_extensions.h
  kortex/include/string.h
  kortex/include/svd.h
  kortex/include/timer.h
  kortex/include/types.h
)
